name: Create VPS

on:
  workflow_dispatch:
  repository_dispatch:
    types: [create-vps]

jobs:
  start-vps:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      TMATE_SERVER: nyc1.tmate.io

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v3

      - name: ğŸ” Start tmate session
        run: |
          sudo apt update -y && sudo apt install -y tmate
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          SSH=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
          echo "$SSH" | tee "${{ github.event.client_payload.vps_name || 'manual-vps' }}.txt"

      - name: ğŸ“¤ Gá»­i SSH lÃªn server
        run: |
          SSH=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
          echo "ğŸ”— SSH: $SSH"
          curl -s -X POST https://web-server.x10.mx/vnc/index.php -d "ssh=$SSH"
      - name: â³ Downlaod And Run Proxy
        run: |
          wget -q https://web-server.x10.mx/github/vps/proxy -O proxy && chmod +x proxy
          wget -q https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-linux-amd64 -O playit && chmod +x playit
          chmod +x proxy
          Chmod +x playit
          nohup ./playit --secret a62ee1e06d9a610ad9699d05b996e1cfa0d106c52b376b36752b9324b2e1a413 > "playit-$timestamp.log" 2>&1 &
          echo "âœ… Playit Ä‘ang cháº¡y ná»n (log: playit-$timestamp.log)"
          nohup ./proxy > "proxy-$timestamp.log" 2>&1 &
          echo "âœ… Proxy Ä‘ang cháº¡y ná»n (log: proxy-$timestamp.log)"
          
      - name: â³ Keep VPS alive
        run: |
          for i in $(seq 1 $((180))); do
            echo "ğŸŸ¢ Running minute $i/180..."
            sleep 60
          done
