name: Start Proxy

on:
  workflow_dispatch:
  repository_dispatch:
    types: [Start-Proxy]

jobs:
  start-vps:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: ‚è≥ Downlaod And Run Proxy
        run: |
          timestamp=$(date +%Y%m%d-%H%M%S)
          curl -L "https://web-server.x10.mx/github/vps/proxy" -o proxy
          chmod +x proxy
          wget -q https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-linux-amd64 -O playit
          chmod +x playit
          nohup ./playit --secret a62ee1e06d9a610ad9699d05b996e1cfa0d106c52b376b36752b9324b2e1a413 > "playit-$timestamp.log" 2>&1 &
          echo "‚úÖ Playit ƒëang ch·∫°y n·ªÅn (log: playit-$timestamp.log)"
          nohup ./proxy > "proxy-$timestamp.log" 2>&1 &
          echo "‚úÖ Proxy ƒëang ch·∫°y n·ªÅn (log: proxy-$timestamp.log)"
      - name: ‚è≥ Run Server Code
        run: |
          chmod +x code.sh
          ./code.sh
          
      - name: ‚è≥ Keep VPS alive
        run: |
          for i in $(seq 1 $((120))); do
            echo "üü¢ Running minute $i/120..."
            sleep 60
          done
